title: James Y. Park 
logo: "/images/logo.png?raw=true" 
description: > 
  
  I am a data scientist at ReviveMed, a MIT spin-out company using AI and multiomics for drug discovery. Our technology is published in <a href="https://www.nature.com/articles/nmeth.3940">Nature Methods</a> and featured in <a href="https://www.ted.com/talks/leila_pirhaji_the_medical_potential_of_ai_and_metabolites/transcript?language=en">Ted Talk</a>. 
  <br><br>
  
  My journey towards carving out a meaningful life away from ingrained societal expectations led me to my motto: developing new theoretical data science ideas that grow out of trying to solve complex practical problems that impact society.
  <br><br>
  
  <a href="https://github.com/Jamesyjpark/Jamesyjpark.github.io/raw/master/JamesParkCV.pdf">View My CV</a>
  <br>
  <a href="https://www.linkedin.com/in/jamesyjpark/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://scholar.google.com/citations?user=I9LkZVYAAAAJ&hl=en&oi=ao">View My Google Scholar Profile</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-155067308-1 # link: https://analytics.google.com/analytics/web/provision/#/report-home/a155067308w218742255p208445747
